export default {
    en: {
        //登入頁面
        account: 'account',
        password: 'password',
        verifyNum: 'verify number',
        verifyRe: 'Refreshing number',
        logIn: 'Log in',
        logErrTitle: 'Wrong Login Info',
        logErrMsg: 'Please correct your Info',
        noAccount: 'No Account',
        forgotAccount: 'Forget Account',
        settingPage: 'Setting',

        //主頁
        lordTable: 'LT',
        prayer: 'PM',
        homeMet: 'HM',
        grouMet: 'GM',
        gospVis: 'GV',
        rollCall: 'RollCall',
        statis: 'Statistic',
        visitList: 'VisitList',
        setting: 'Setting',
        addNew: 'Add',
        freList:'Frequent List',

        // 創建帳號頁面
        withFB: '| Create account by Facebook',
        withG: '| Create account by Google',
        lowAuth: 'Limits of authority',
        lowAuthSub: 'Only low authority permitted with creating accounts by Facebook and Google',

        // 設定頁面
        interface: 'Interface',
        theme: 'Theme',
        fonstSize: 'Font size',
        language: 'Language',
        eng: 'English',
        chzh: 'Chinese',
        small: 'S',
        middle: 'M',
        large: 'L',
        Xlarge: 'XL',
        lineSpace: 'Lines space',
        theme1: 'Theme 1',
        theme2: 'Theme 2',
        theme3: 'Theme 3',

        // 點名
        search: 'Search',
        lordTableFull: 'Lord table meeting',
        prayerFull: 'Prayer meeting',
        homeMetFull: 'Appintment',
        grouMetFull: 'Group meeting',
        gospVisFull: 'Gospel visiting',
        
        //篩選
        gender: 'Select gender',
        status: 'Select status',
        identity: 'Select identity',
        group: 'Select group',
        all: 'all',
        male: 'male',
        female: 'female',
        enable: 'enable',
        disable: 'disable',
        visit: 'visit',
        moved: 'moved',
        dead: 'dead',
        saint: 'saint',
        gospelFriend: 'gospel friend',
        beforeSchool: 'before school',
        primarySchool: 'primary school',
        secondarySchool: 'secondary school',
        teritiarySchool: 'teritiary school',
        working: 'working',
        mature: 'mature',
        middleAge: 'middle age',
        elder: 'elder',
    },
    zh: {
        //登入頁面
        account: '帳號',
        password: '密碼',
        verifyNum: '驗證碼',
        verifyRe: '刷新驗證碼',
        logIn: '登入',
        logErrTitle: '登入資訊有誤',
        logErrMsg: '請重新填寫',
        noAccount: '沒有帳號',
        forgotAccount: '忘記帳號',
        settingPage: '設定',

        //主頁
        lordTable: '主',
        prayer: '禱',
        homeMet: '家',
        grouMet: '排',
        gospVis: '福',
        rollCall: '點名',
        statis: '統計',
        visitList: '看望',
        setting: '設定',
        addNew: '新增',
        freList: '常用名單',

        // 創建帳號頁面
        withFB: '| 用Facebook創立帳號',
        withG: '| 用Google創立帳號',
        lowAuth: '權限說明',
        lowAuthSub: '使用Facebook及Google創立帳號只擁有最低權限',

        // 設定頁面
        interface: '介面',
        theme: '主題顏色',
        fonstSize: '字體大小',
        language: '語言',
        eng: '英',
        chzh: '中',
        small: '小',
        middle: '適中',
        large: '大',
        Xlarge: '極大',
        lineSpace: '行距',
        theme1: '主題1',
        theme2: '主題2',
        theme3: '主題3',

        // 點名
        search: '搜尋',
        lordTableFull: '主日聚會',
        prayerFull: '禱告聚會',
        homeMetFull: '家聚會',
        grouMetFull: '小排聚會',
        gospVisFull: '福音出訪',
        
        //篩選
        gender: '選擇性別',
        status: '選擇狀態',
        identity: '選擇身分',
        group: '選擇群組',
        all: '全部',
        male: '男性',
        female: '女性',
        enable: '正常',
        disable: '停用',
        visit: '來訪',
        moved: '遷出',
        dead: '主裏安睡',
        saint: '聖徒',
        gospelFriend: '福音朋友',
        beforeSchool: '學齡前',
        primarySchool: '小學',
        secondarySchool: '中學',
        teritiarySchool: '大專',
        working: '青職',
        mature: '青壯',
        middleAge: '中壯',
        elder: '年長',
    }
}